# Generated by Django 3.0 on 2022-03-20 20:14

from django.db import migrations


def duplicate_table_adress(apps, schema_editor):
    Address = apps.get_model('oc_lettings_site', 'Address')
    NewAddresse = apps.get_model('lettings', 'Address')
    address_list = list()
    for adress in Address.objects.all():
        new = NewAddresse(number=adress.number,
                          street=adress.street,
                          city=adress.city,
                          state=adress.state,
                          zip_code=adress.zip_code,
                          country_iso_code=adress.country_iso_code)
        address_list.append(new)
    NewAddresse.objects.bulk_create(address_list)


def duplicate_table_lettings(apps, schema_editor):
    Lettings = apps.get_model('oc_lettings_site', 'Letting')
    NewLettings = apps.get_model('lettings', 'Letting')
    lettings_list = list()
    for letting in Lettings.objects.all():
        new = NewLettings(title=letting.title,
                          address=letting.address)
        lettings_list.append(new)
    NewLettings.objects.bulk_create(lettings_list)


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(duplicate_table_adress),
        migrations.RunPython(duplicate_table_lettings),
    ]