# Generated by Django 3.0 on 2022-03-20 20:14

from django.db import migrations
from django.db import transaction


def duplicate_table_adress(apps, schema_editor):
    Address = apps.get_model('oc_lettings_site', 'Address')
    NewAddresse = apps.get_model('lettings', 'Address')
    address_list = list()
    for address in Address.objects.all():
        new = NewAddresse(number=address.number,
                          street=address.street,
                          city=address.city,
                          state=address.state,
                          zip_code=address.zip_code,
                          country_iso_code=address.country_iso_code)
        address_list.append(new)
    NewAddresse.objects.bulk_create(address_list)



def duplicate_table_lettings(apps, schema_editor):
    from django.apps import apps
    
    Lettings = apps.get_model('oc_lettings_site', 'Letting')
    Address = apps.get_model('lettings', 'Address')
    NewLettings = apps.get_model('lettings', 'Letting')
    lettings_list = list()
    for letting in Lettings.objects.all():
        address = Address.objects.get(pk=letting.address.pk)
        new = NewLettings(title=letting.title,
                          address=address)
        lettings_list.append(new)
    NewLettings.objects.bulk_create(lettings_list)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(duplicate_table_adress),
        migrations.RunPython(duplicate_table_lettings),
    ]
